# @package _global_
# Override configuration for fair_mon dataset
dataset_name: fair_mon
robot_type: allegro
viewer: rerun-mujoco
embodiment_type: right
task: cat
rerun_spawn: true
ref_dt: 0.05
max_sim_steps: -1
horizon: 0.8
ctrl_dt: 0.1
knot_dt: 0.2
num_dr: 1
perturb_torque: 0.0
pos_noise_scale: 0.05
rot_noise_scale: 0.05
joint_noise_scale: 0.1
improvement_check_steps: 2
max_num_iterations: 16
temperature: 1.0
# original reference is bad, so we put smaller scale on tracking wrist pose
base_pos_rew_scale: 0.1
base_rot_rew_scale: 0.03
